### ISSUE TITLE
missing lib directory? 

### ISSUE THREAD

**Issue by cavnara-avalon** [robertkowalski/couchdb-graphql#1]
Hey there, 

Just tried to run this example, and I noticed there are resolvers located in lib/resolvers, but there's no lib directory. Were they omitted? I'm really interested in seeing how you built your resolvers to interface with Couchbase.

**Comment by robertkowalski** [comment]
thanks for the report

fixed with:

0ee5011c84551d8b0317609f6710d3e5556858aa
7c8ba70cf32836880cd7ebcf64002d23a401572f

**Comment by robertkowalski** [comment]
latest version on master

**Comment by robertkowalski** [comment]
also: i don't use couchbase. apache couchdb and couchbase are different products.
